exclusions:
  - id: Exclusions.Test
    name: Exclude test source code
    patterns:
      - "(.*/test(s)?/.*)|/Test[A-Z]|Test[.]"

  - id: Exclusions.Empty
    name: Exclude file which cannot be read
    patterns:
      - "<empty>|<unknownFullName>"
